// <auto-generated />
using FWPS.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace FWPS.Migrations
{
    [DbContext(typeof(FwpsDbContext))]
    [Migration("20180430112600_roomNewFile")]
    partial class roomNewFile
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FWPS.Models.ClimateControlItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Command");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<int>("HumidityLevel");

                    b.Property<bool>("IsHeaterOn");

                    b.Property<bool>("IsRun");

                    b.Property<bool>("IsVentilationOn");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int>("MaxHumidity");

                    b.Property<int>("MaxTemperature");

                    b.Property<int>("MinHumidity");

                    b.Property<int>("MinTemperature");

                    b.Property<int>("TemperatureLevel");

                    b.HasKey("Id");

                    b.ToTable("ClimateControlItems");
                });

            modelBuilder.Entity("FWPS.Models.CurtainItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Command");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsRun");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<int>("LightIntensity");

                    b.Property<int>("MaxLightIntensity");

                    b.Property<string>("Status");

                    b.HasKey("Id");

                    b.ToTable("CurtainItems");
                });

            modelBuilder.Entity("FWPS.Models.HodoorItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Command");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsRun");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<bool>("OpenStatus");

                    b.HasKey("Id");

                    b.ToTable("HodoorItems");
                });

            modelBuilder.Entity("FWPS.Models.IpItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("Ip");

                    b.Property<DateTime>("LastModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("IpItems");
                });

            modelBuilder.Entity("FWPS.Models.LightItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Command");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsOn");

                    b.Property<bool>("IsRun");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<DateTime>("SleepTime");

                    b.Property<DateTime>("WakeUpTime");

                    b.HasKey("Id");

                    b.ToTable("LightItems");
                });

            modelBuilder.Entity("FWPS.Models.LoginItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("LoginItems");
                });

            modelBuilder.Entity("FWPS.Models.MailItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Body");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<string>("From");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<string>("Subject");

                    b.Property<string>("To");

                    b.HasKey("Id");

                    b.ToTable("MailItems");
                });

            modelBuilder.Entity("FWPS.Models.PoombaItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("CleaningTime");

                    b.Property<string>("Command");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsRun");

                    b.Property<DateTime>("LastModifiedDate");

                    b.HasKey("Id");

                    b.ToTable("PoombaItems");
                });

            modelBuilder.Entity("FWPS.Models.Room", b =>
                {
                    b.Property<string>("RoomName")
                        .ValueGeneratedOnAdd();

                    b.Property<long?>("PoombaItemId");

                    b.HasKey("RoomName");

                    b.HasIndex("PoombaItemId");

                    b.ToTable("Room");
                });

            modelBuilder.Entity("FWPS.Models.SnapBoxItem", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Checksum");

                    b.Property<DateTime>("CreatedDate");

                    b.Property<DateTime>("LastModifiedDate");

                    b.Property<bool>("MailReceived");

                    b.Property<string>("PowerLevel");

                    b.Property<string>("ReceiverEmail");

                    b.Property<string>("SnapBoxId");

                    b.HasKey("Id");

                    b.ToTable("SnapBoxItems");
                });

            modelBuilder.Entity("FWPS.Models.Room", b =>
                {
                    b.HasOne("FWPS.Models.PoombaItem")
                        .WithMany("Rooms")
                        .HasForeignKey("PoombaItemId");
                });
#pragma warning restore 612, 618
        }
    }
}
